---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openshift-nginx-redirect.name" . }}
  labels:
    {{- include "openshift-nginx-redirect.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 8080;
        rewrite ^/(.*)$ http://{{ .Values.redirectTargetDomain | required "redirectTargetDomain value is required" }}/$1 permanent;
      }
    }
