---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openshift-nginx-redirect.name" . }}
  labels:
    {{- include "openshift-nginx-redirect.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openshift-nginx-redirect.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "openshift-nginx-redirect.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: server
        command:
        - nginx
        - -c
        - /config/nginx.conf
        - -g
        - "daemon off;"
        image: "{{ .Values.image }}"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 3
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: {{ include "openshift-nginx-redirect.name" . }}
