---
image: "image-registry.openshift-image-registry.svc:5000/openshift/nginx:latest"

redirectTargetDomain:

replicaCount: 1

resources:
  limits:
    cpu: "1"
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

route:
  host:
  certManager:
    enable: false
    duration: 720h0m0s
    issuerRef:
      name: letsencrypt
      kind: ClusterIssuer
      group: cert-manager.io
    privateKey:
      algorithm: RSA
      encoding: PKCS1
      size: 4096
    renewBefore: 360h0m0s
  certUtilsOperator:
    enable: false
